// Every constant the model uses, with its value, unit, fidelity level and source. This file is the
// single source of truth: code reads constants from here, and FIDELITY.md lists them from here.
//
// A parameter is free when we set it ourselves (level 1 or 0), and the free ones count against the
// budget in PLAN.md §6.2. Calibrated parameters (level 1) are tuned in milestone 0c by one CMA-ES
// procedure, within bounds set here before it runs (PLAN.md §7.3); until then their value and bounds are
// null. A parameter fixed in advance (level 0) either has a value or is set by a stated rule. Every
// parameter says what new data or research would raise it (spec §1.3).

import type { CitationId } from './citations.ts';
import { isFree, type Level } from './levels.ts';

export type Subsystem = 'neural' | 'sensing' | 'rhythm' | 'muscle' | 'body' | 'environment';

export interface Param {
  name: string;
  symbol: string;
  // Null for a calibrated parameter not yet calibrated, and for one set by a rule.
  value: number | null;
  unit: string;
  level: Level;
  subsystem: Subsystem;
  sources: readonly CitationId[];
  note: string;
  // How a value set by a rule is found, for a parameter fixed in advance.
  rule?: string;
  // What new data or research would raise its level.
  upgrade: string;
  // What a calibrated parameter is tuned against (PLAN.md §7.3), and the range it may move within.
  calibratedAgainst?: string;
  bounds?: readonly [number, number] | null;
}

export const FREE_PARAMETER_BUDGET = 14;
const CALIBRATION_TARGETS =
  'undulation frequency, wavelength, speed and the spontaneous reversal rate, by one CMA-ES procedure (PLAN §7.3)';

export const PARAMS = {
  // Neurons and synapses (PLAN §3.2).
  membraneCapacitance: {
    name: 'Membrane capacitance',
    symbol: 'C',
    value: 1,
    unit: 'pF',
    level: 3,
    subsystem: 'neural',
    sources: ['kunert2014', 'kunertgraf2017'],
    note: "Kunert-Graf et al. 2017 (Table 1) give G_c = 10 pS and C = 1 pF. Neural Interactome's code runs the same model 1.5× slower (1.5 pF); only the port check uses that.",
    upgrade: 'Per-class capacitance from patch-clamp recordings',
  },
  leakConductance: {
    name: 'Leak conductance',
    symbol: 'G_c',
    value: 10,
    unit: 'pS',
    level: 3,
    subsystem: 'neural',
    sources: ['kunert2014', 'kunertgraf2017'],
    note: 'The same for every neuron.',
    upgrade: 'Per-class input resistance from patch-clamp recordings',
  },
  leakPotential: {
    name: 'Leak potential',
    symbol: 'E_c',
    value: -35,
    unit: 'mV',
    level: 3,
    subsystem: 'neural',
    sources: ['wicks1996', 'kunert2014'],
    note: 'From Wicks, Roehrig & Rankin, via Kunert et al.',
    upgrade: 'Measured resting potentials per neuron class',
  },
  reversalExcitatory: {
    name: 'Excitatory reversal potential',
    symbol: 'E_exc',
    value: 0,
    unit: 'mV',
    level: 3,
    subsystem: 'neural',
    sources: ['wicks1996'],
    note: 'Set per connection by its sign, where Neural Interactome sets it per presynaptic neuron.',
    upgrade: 'Measured reversal potentials of C. elegans excitatory ligand-gated channels',
  },
  reversalInhibitory: {
    name: 'Inhibitory reversal potential',
    symbol: 'E_inh',
    value: -48,
    unit: 'mV',
    level: 3,
    subsystem: 'neural',
    sources: ['wicks1996', 'kim2019'],
    note: 'Wicks, Roehrig & Rankin 1996 give −48 mV in their Table 1 but −45 mV in their text. Kunert et al. 2014 and Kunert-Graf et al. 2017 use −45 mV; Neural Interactome, whose code the port check runs, uses −48 mV, and so does Wormlight.',
    upgrade: 'Measured reversal potentials of C. elegans GABA and glutamate-gated chloride channels',
  },
  sigmoidWidth: {
    name: 'Synaptic activation sigmoid width',
    symbol: 'β',
    value: 0.125,
    unit: 'mV⁻¹',
    level: 3,
    subsystem: 'neural',
    sources: ['wicks1996'],
    note: '',
    upgrade: 'Measured voltage dependence of release at graded synapses',
  },
  synapticRise: {
    name: 'Synaptic rise rate',
    symbol: 'a_r',
    value: 1,
    unit: 's⁻¹',
    level: 3,
    subsystem: 'neural',
    sources: ['kunertgraf2017'],
    note: 'Kunert-Graf et al. 2017 (Table 1) give a_r = 1 s⁻¹ and a_d = 5 s⁻¹.',
    upgrade: 'Measured synaptic kinetics',
  },
  synapticDecay: {
    name: 'Synaptic decay rate',
    symbol: 'a_d',
    value: 5,
    unit: 's⁻¹',
    level: 3,
    subsystem: 'neural',
    sources: ['kunertgraf2017'],
    note: 'As above.',
    upgrade: 'Measured synaptic kinetics',
  },
  conductancePerSynapse: {
    name: 'Conductance per Varshney synapse',
    symbol: 'g',
    value: 100,
    unit: 'pS',
    level: 3,
    subsystem: 'neural',
    sources: ['kunert2014'],
    note: 'For gap junctions and chemical synapses alike, per unit of Varshney et al. 2011 count.',
    upgrade: 'Per-connection physiology (paired recordings, voltage imaging)',
  },
  cookToVarshneyChemical: {
    name: 'Cook-to-Varshney scale, chemical synapses',
    symbol: 'k_chem',
    value: 0.3444,
    unit: 'Varshney units per EM section',
    level: 2,
    subsystem: 'neural',
    sources: ['varshney2011', 'cook2019'],
    note: "Matches the two datasets' totals over the 279 neurons they share, autapses excluded as in Neural Interactome's matrices. Connections the two share end up about 0.69× their Neural Interactome strength.",
    upgrade: "A model parameterised on Cook's counts directly, or per-connection physiology",
  },
  cookToVarshneyGap: {
    name: 'Cook-to-Varshney scale, gap junctions',
    symbol: 'k_gap',
    value: 0.2055,
    unit: 'Varshney units per EM section',
    level: 2,
    subsystem: 'neural',
    sources: ['varshney2011', 'emmons2024'],
    note: "As above, on Emmons 2024's corrected gap junctions; shared connections end up about 0.63× their Neural Interactome strength.",
    upgrade: "A model parameterised on Cook's counts directly, or per-connection physiology",
  },
  noiseIntensity: {
    name: 'Neural noise intensity',
    symbol: 'σ_n',
    value: null,
    unit: 'pA·√s',
    level: 1,
    subsystem: 'neural',
    sources: ['gray2005'],
    note: 'White current noise, drawn each step with standard deviation σ_n/√dt.',
    calibratedAgainst: CALIBRATION_TARGETS,
    upgrade: 'Measured noise statistics of C. elegans neurons',
    bounds: null,
  },

  // Sensing (PLAN §4.1, §4.2).
  awcAdaptationScale: {
    name: 'AWC adaptive threshold scale',
    symbol: 'K',
    value: 5.5,
    unit: 'µM',
    level: 3,
    subsystem: 'sensing',
    sources: ['levy2020'],
    note: "Read from the authors' code; fitted to butanone in microfluidic devices.",
    upgrade: 'Threshold measurements on assay plates',
  },
  awcAdaptationTime: {
    name: 'AWC adaptive threshold time constant',
    symbol: 'τ',
    value: 17,
    unit: 's',
    level: 3,
    subsystem: 'sensing',
    sources: ['levy2020'],
    note: 'As above.',
    upgrade: 'Threshold measurements on assay plates',
  },
  awcGain: {
    name: 'AWC transduction gain',
    symbol: 'g_AWC',
    value: null,
    unit: 'pA',
    level: 0,
    subsystem: 'sensing',
    sources: [],
    note: 'Never tuned against chemotaxis.',
    rule: 'Set once, on the intact real wiring, so that removing odour from the adapted start concentration depolarises AWC by 16 mV (2/β).',
    upgrade: 'Current-clamp recordings from AWC',
  },
  touchAmplitude: {
    name: 'Touch stimulus amplitude',
    symbol: 'ΔV_touch',
    value: 10,
    unit: 'mV above rest',
    level: 0,
    subsystem: 'sensing',
    sources: [],
    note: 'Applied as one current per receptor, computed from its input conductance in the intact real wiring, and the same for every brain and lesion.',
    upgrade: 'Recorded touch receptor currents',
  },
  touchDuration: {
    name: 'Touch stimulus duration',
    symbol: 't_touch',
    value: 500,
    unit: 'ms',
    level: 0,
    subsystem: 'sensing',
    sources: [],
    note: '',
    upgrade: 'Recorded touch receptor currents',
  },

  // Rhythm and proprioception (PLAN §4.3).
  headSwitchDerivativeWeight: {
    name: 'Head switch derivative weight',
    symbol: 'b',
    value: 46,
    unit: 'ms',
    level: 2,
    subsystem: 'rhythm',
    sources: ['ji2021'],
    note: 'Fitted in a 120 mPa·s fluid, so adapted on agar.',
    upgrade: 'The same phase-response fit made on agar',
  },
  headSwitchThreshold: {
    name: 'Head switch threshold',
    symbol: 'P_th',
    value: 2.33,
    unit: 'dimensionless',
    level: 2,
    subsystem: 'rhythm',
    sources: ['ji2021'],
    note: 'As above.',
    upgrade: 'The same phase-response fit made on agar',
  },
  headSwitchRegionStart: {
    name: 'Head switch curvature region, front',
    symbol: 's_head,0',
    value: 0.1,
    unit: 'body coordinate',
    level: 2,
    subsystem: 'rhythm',
    sources: ['ji2021'],
    note: 'The switch reads the scaled curvature K = κL averaged over body coordinates 0.1–0.3, the head region where Ji et al. measured it and fitted b and P_th.',
    upgrade: 'The same phase-response fit made on agar',
  },
  headSwitchRegionEnd: {
    name: 'Head switch curvature region, back',
    symbol: 's_head,1',
    value: 0.3,
    unit: 'body coordinate',
    level: 2,
    subsystem: 'rhythm',
    sources: ['ji2021'],
    note: 'As above.',
    upgrade: 'The same phase-response fit made on agar',
  },
  headSwitchGain: {
    name: 'Head switch current gain',
    symbol: 'g_sw',
    value: null,
    unit: 'pA',
    level: 1,
    subsystem: 'rhythm',
    sources: [],
    note: '',
    calibratedAgainst: CALIBRATION_TARGETS,
    upgrade: 'Recordings of the head rhythm generator',
    bounds: null,
  },
  oscillatorExcitability: {
    name: 'Oscillator excitability',
    symbol: 'g_osc',
    value: null,
    unit: 'pS',
    level: 1,
    subsystem: 'rhythm',
    sources: [],
    note: 'Shared by the A- and B-type oscillators.',
    calibratedAgainst: CALIBRATION_TARGETS,
    upgrade: 'A parameterised model of the A- and B-type rhythms',
    bounds: null,
  },
  oscillatorRecoveryTime: {
    name: 'Oscillator recovery time',
    symbol: 'τ_w',
    value: null,
    unit: 's',
    level: 1,
    subsystem: 'rhythm',
    sources: [],
    note: 'Shared by the A- and B-type oscillators.',
    calibratedAgainst: CALIBRATION_TARGETS,
    upgrade: 'A parameterised model of the A- and B-type rhythms',
    bounds: null,
  },
  oscillatorDriveThreshold: {
    name: 'B-type oscillator drive threshold',
    symbol: 'θ_osc',
    value: null,
    unit: 'mV',
    level: 1,
    subsystem: 'rhythm',
    sources: [],
    note: "B-type neurons and the head switch run only above it, which AVB's drive supplies.",
    calibratedAgainst: CALIBRATION_TARGETS,
    upgrade: 'Measured AVB drive at the onset of B-type oscillation',
    bounds: null,
  },
  proprioceptiveReach: {
    name: 'Proprioceptive reach',
    symbol: 'ℓ_p',
    value: 0.2,
    unit: 'body lengths',
    level: 3,
    subsystem: 'rhythm',
    sources: ['wen2012'],
    note: "About 200 µm in front of a B-type neuron's muscles; mirrored behind for A-type neurons (a hypothesis).",
    upgrade: 'Identified stretch receptors and their receptive fields',
  },
  proprioceptiveGain: {
    name: 'Proprioceptive gain',
    symbol: 'g_p',
    value: null,
    unit: 'pA',
    level: 1,
    subsystem: 'rhythm',
    sources: [],
    note: 'One gain for A- and B-type neurons.',
    calibratedAgainst: CALIBRATION_TARGETS,
    upgrade: 'Identified stretch receptors and their gain',
    bounds: null,
  },

  // Neuromuscular transfer and muscles (PLAN §4.4).
  neuromuscularGain: {
    name: 'Neuromuscular gain',
    symbol: 'g_nmj',
    value: null,
    unit: 'per EM section',
    level: 1,
    subsystem: 'muscle',
    sources: [],
    note: '',
    calibratedAgainst: CALIBRATION_TARGETS,
    upgrade: 'Measured transfer from motor neuron activity to muscle activation',
    bounds: null,
  },
  neuromuscularThreshold: {
    name: 'Neuromuscular threshold',
    symbol: 'θ_nmj',
    value: null,
    unit: 'EM sections',
    level: 1,
    subsystem: 'muscle',
    sources: [],
    note: '',
    calibratedAgainst: CALIBRATION_TARGETS,
    upgrade: 'Measured transfer from motor neuron activity to muscle activation',
    bounds: null,
  },
  muscleTimeConstant: {
    name: 'Muscle time constant',
    symbol: 'τ_M',
    value: 100,
    unit: 'ms',
    level: 3,
    subsystem: 'muscle',
    sources: ['boyle2012', 'ji2021'],
    note: "Ji et al.'s muscle switching time is also 100 ms.",
    upgrade: 'Direct measurements of C. elegans body wall muscle kinetics',
  },

  // Body (PLAN §5.1).
  bodyLength: {
    name: 'Body length',
    symbol: 'L',
    value: 1,
    unit: 'mm',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: 'Speeds and wavelengths are compared in body lengths, so this sets only the scale.',
    upgrade: 'Per-animal lengths, which vary with age and strain',
  },
  bodyUnits: {
    name: 'Body units',
    symbol: 'M',
    value: 48,
    unit: 'units',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: 'Built from 49 rods.',
    upgrade: 'A continuum body model',
  },
  bodyRadius: {
    name: 'Body radius',
    symbol: 'R',
    value: 40,
    unit: 'µm',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: "The outline is a prolate ellipse with this minor radius: rod i's radius is R|sin(cos⁻¹((i − (M/2 + 1))/(M/2 + 0.2)))|, the major radius a little over L/2 so the tips keep a width (their eq. 2).",
    upgrade: 'Measured radius profiles',
  },
  lateralStiffness: {
    name: 'Lateral (cuticle) stiffness',
    symbol: 'κ_L',
    value: 0.02,
    unit: 'N m⁻¹',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: 'Table 1 gives (M/24) × 0.01 and prints the unit as kg·s⁻¹; a spring constant is in kg·s⁻², as their code uses it. Chosen with the damping below so a flaccid body straightens slowly on agar.',
    upgrade: 'Measured cuticle and body-wall elasticity',
  },
  diagonalStiffness: {
    name: 'Diagonal (pressure) stiffness',
    symbol: 'κ_D',
    value: 350,
    unit: '× κ_L',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: 'The diagonal elements stand in for the hydrostatic pressure that keeps each segment from collapsing.',
    upgrade: 'A model of internal pressure',
  },
  lateralDamping: {
    name: 'Lateral damping',
    symbol: 'β_L',
    value: 0.025,
    unit: 's × κ_L',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: '',
    upgrade: 'Measured body-wall viscoelasticity',
  },
  diagonalDamping: {
    name: 'Diagonal damping',
    symbol: 'β_D',
    value: 0.01,
    unit: 's × κ_D',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: '',
    upgrade: 'Measured body-wall viscoelasticity',
  },
  muscleStiffness: {
    name: 'Muscle stiffness at full activation',
    symbol: 'κ_0M',
    value: 20,
    unit: '× κ_L',
    level: 3,
    subsystem: 'muscle',
    sources: ['boyle2012'],
    note: 'A muscle is a spring and damper beside the cuticle whose stiffness, damping and shortened rest length all scale with F_max,m σ(A), a simple Hill-like length-force and force-velocity relation (their eqs. 5–7).',
    upgrade: 'Measured force-length and force-velocity curves of body wall muscle',
  },
  muscleDamping: {
    name: 'Muscle damping at full activation',
    symbol: 'β_0M',
    value: 100,
    unit: '× β_L',
    level: 3,
    subsystem: 'muscle',
    sources: ['boyle2012'],
    note: '',
    upgrade: 'Measured force-velocity curves of body wall muscle',
  },
  muscleShortening: {
    name: 'Muscle shortening at full activation',
    symbol: 'Δ_M',
    value: 0.65,
    unit: 'dimensionless',
    level: 3,
    subsystem: 'muscle',
    sources: ['boyle2012'],
    note: 'A fully active muscle pulls its rest length down to L_min = L_0L (1 − Δ_M (R_m + R_m+1)/2R), scaled by the local radius so every segment can reach the same curvature.',
    upgrade: 'Measured sarcomere shortening limits',
  },
  muscleEfficacy: {
    name: 'Muscle efficacy at the head',
    symbol: 'F_max',
    value: 0.7,
    unit: 'dimensionless',
    level: 3,
    subsystem: 'muscle',
    sources: ['boyle2012'],
    note: "Scales each muscle's stiffness, damping and shortening: F_max,m = F_max (1 − f (m − 1)/M), which is Table 1's 0.70 − 0.42 (m − 1)/M.",
    upgrade: 'Measured force along the body',
  },
  muscleEfficacyFall: {
    name: 'Fall in muscle efficacy from head to tail',
    symbol: 'f',
    value: 0.6,
    unit: 'dimensionless',
    level: 3,
    subsystem: 'muscle',
    sources: ['boyle2012'],
    note: "The share of F_max lost by the tail, which gives the body's decreasing curvature from head to tail.",
    upgrade: 'Measured force along the body',
  },
  headMuscleEfficacy: {
    name: 'Head muscle weakening',
    symbol: 'F_max,1 / F_max',
    value: 2 / 3,
    unit: 'dimensionless',
    level: 3,
    subsystem: 'muscle',
    sources: ['boyle2012'],
    note: 'The first muscle gets F_max × 2/3, so the tip of the head does not over-bend (Table 1).',
    upgrade: 'Measured force along the body',
  },
  dragParallel: {
    name: 'Agar drag coefficient, tangential',
    symbol: 'C∥',
    value: 3.2e-3,
    unit: 'kg s⁻¹',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: "Whole-worm value. Each of the 49 rods takes C/98, as the authors' code does, so a body moving as a whole feels C/2.",
    upgrade: "Drag measured on agar of the assay's concentration",
  },
  dragPerpendicular: {
    name: 'Agar drag coefficient, normal',
    symbol: 'C⊥',
    value: 128e-3,
    unit: 'kg s⁻¹',
    level: 3,
    subsystem: 'body',
    sources: ['boyle2012'],
    note: 'As above; 40 times the tangential value.',
    upgrade: "Drag measured on agar of the assay's concentration",
  },

  // Environment (PLAN §5.2).
  butanoneDiffusion: {
    name: 'Butanone diffusion coefficient in air',
    symbol: 'D',
    value: 0.091,
    unit: 'cm² s⁻¹',
    level: 3,
    subsystem: 'environment',
    sources: ['lugg1968', 'tang2015'],
    note: 'Measured at 298 K by Lugg, as compiled by Tang et al.',
    upgrade: "A measurement at the assay's temperature and humidity",
  },
  odourDecayLength: {
    name: 'Odour decay length',
    symbol: '√(D/k)',
    value: 3,
    unit: 'cm',
    level: 0,
    subsystem: 'environment',
    sources: [],
    note: 'Sets the first-order loss rate k.',
    upgrade: 'Measured butanone fields on assay plates',
  },
  odourReleaseRate: {
    name: 'Odour release rate',
    symbol: 'Q',
    value: null,
    unit: 'µM cm² s⁻¹',
    level: 0,
    subsystem: 'environment',
    sources: [],
    note: '',
    rule: "Set so that the steady concentration at the 0.5 cm capture radius equals K, the top of the adaptation model's working range.",
    upgrade: 'Measured butanone fields on assay plates',
  },
  lawnDiameter: {
    name: 'Food lawn diameter',
    symbol: 'd_lawn',
    value: 1,
    unit: 'cm',
    level: 0,
    subsystem: 'environment',
    sources: [],
    note: '',
    upgrade: 'A lawn size the reference assays specify',
  },
  dishDiameter: {
    name: 'Dish diameter',
    symbol: 'd_dish',
    value: 10,
    unit: 'cm',
    level: 3,
    subsystem: 'environment',
    sources: ['bargmann1993'],
    note: 'The standard chemotaxis plate.',
    upgrade: 'None needed: it is the assay protocol',
  },
  spotOffset: {
    name: 'Odour and control spots from the dish edge',
    symbol: 'x_spot',
    value: 0.5,
    unit: 'cm',
    level: 3,
    subsystem: 'environment',
    sources: ['bargmann1993'],
    note: '',
    upgrade: 'None needed: it is the assay protocol',
  },
} as const satisfies Record<string, Param>;

export type ParamId = keyof typeof PARAMS;

export const freeParams = (): ParamId[] => (Object.keys(PARAMS) as ParamId[]).filter((id) => isFree(PARAMS[id].level));
