// The build's reports: the sign cross-check against Creamer et al.'s fitted weights, and a summary of
// what the build read, kept, ignored and assigned.

import type { Chemical, WormlightData } from '../../src/data/schema.ts';
import { grouped } from '../../src/science/facts.ts';
import { countBySource, edgeKey, type FenyvesSheet, type Override, type SetAside } from './signs.ts';
import type { EigenwormCheck, PostureCheck } from './eigenworms.ts';
import type { Sources } from './sources.ts';
import { table } from './render.ts';

const GENERATED = '<!-- Generated by `npm run data:build`. Do not edit. -->';
const percent = (part: number, whole: number): string => `${((100 * part) / whole).toFixed(1)}%`;
const signText = (sign: number): string => (sign > 0 ? '+' : sign < 0 ? '−' : '0');
// Code-unit order, so the output never depends on the machine's locale.
const byCodeUnit = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

// Creamer, Leifer & Pillow's table: presynaptic cell, postsynaptic cell, signed weight.
export function parseCreamer(csv: string, neurons: Set<string>): Map<string, number> {
  const lines = csv.trim().split(/\r?\n/);
  if (lines.shift() !== 'presynaptic cell,postsynaptic cell,weight')
    throw new Error('Creamer table: unexpected header');
  const weights = new Map<string, number>();
  for (const line of lines) {
    const [pre, post, weight] = line.split(',');
    if (!neurons.has(pre) || !neurons.has(post)) throw new Error(`Creamer table: unknown neuron in ${line}`);
    weights.set(edgeKey(pre, post), Number(weight));
  }
  return weights;
}

export function crossCheckReport(chemical: Chemical[], creamer: Map<string, number>, sources: Sources): string {
  const licenceKey = sources.datasets.find((d) => d.id === 'creamer-lds')?.licenceText;
  if (!licenceKey) throw new Error('the Creamer dataset names no licence text');
  const covered = chemical.filter((c) => creamer.has(edgeKey(c.pre, c.post)));
  const rows = (['physiology', 'expression', 'rule', 'none'] as const).map((source) => {
    const ofSource = covered.filter((c) => c.signSource === source);
    const signed = ofSource.filter((c) => c.sign !== 0);
    const agree = signed.filter((c) => Math.sign(creamer.get(edgeKey(c.pre, c.post)) ?? 0) === c.sign).length;
    return [
      source,
      String(ofSource.length),
      String(agree),
      String(signed.length - agree),
      String(ofSource.length - signed.length),
    ];
  });
  const disagreements = covered
    .filter((c) => c.sign !== 0 && Math.sign(creamer.get(edgeKey(c.pre, c.post)) ?? 0) !== c.sign)
    .sort((a, b) => b.sections - a.sections || byCodeUnit(edgeKey(a.pre, a.post), edgeKey(b.pre, b.post)));
  return [
    '# Sign cross-check against fitted weights',
    GENERATED,
    `Creamer, Leifer & Pillow fitted a linear dynamical model to whole-brain calcium imaging, constrained to a connectome mask, and released the fitted weights (MIT). Their sign is an independent view of each connection's effect. Wormlight never uses them as strengths. The comparison covers the ${covered.length} of Cook's ${chemical.length} chemical connections that the table also lists; they lie among the head neurons the imaging recorded.`,
    'A disagreement is not an error in either source. The weights are coefficients of a linear model of calcium signals, fitted on a mask that joins chemical and gap-junction edges without telling them apart, with much of the nervous system unrecorded, so a weight can absorb effects that no single synapse carries. They are reported so that a surprising sign can be checked against the physiology.',
    '## Agreement by sign source',
    table(['Sign source', 'Covered', 'Agree', 'Disagree', 'Unsigned here'], rows),
    `## The ${disagreements.length} disagreements, by EM sections`,
    table(
      ['Connection', 'Sections', 'Wormlight sign', 'Source', 'Fitted weight'],
      disagreements.map((c) => [
        `${c.pre} → ${c.post}`,
        String(c.sections),
        signText(c.sign),
        c.signSource,
        String(creamer.get(edgeKey(c.pre, c.post))),
      ]),
    ),
    '## Licence of the fitted weights',
    'The weights quoted above come from `quick_start_examples/model_weights.csv` in `Nondairy-Creamer/Creamer_LDS_2026`, under this licence:',
    `\`\`\`text\n${sources.licenceTexts[licenceKey]}\n\`\`\``,
  ].join('\n\n');
}

export interface BuildFacts {
  data: WormlightData;
  fenyves: FenyvesSheet[];
  setAside: SetAside[];
  overrides: Override[];
  frame: { noseUm: number; tailUm: number };
  axes: { leftLarger: number; pairs: number; nosePairs: number };
  exportCommit: string;
  eigenworms: EigenwormCheck;
  // The real postures, and the share of their variance the first four modes capture.
  postures: PostureCheck & { captured: number };
}

export function buildReport({
  data,
  fenyves,
  setAside,
  overrides,
  frame,
  axes,
  exportCommit,
  eigenworms,
  postures,
}: BuildFacts): string {
  const chemical = data.chemical;
  const connections = chemical.length;
  const sections = chemical.reduce((sum, c) => sum + c.sections, 0);
  const bySource = countBySource(chemical);
  const complexRows = new Map<string, number>();
  for (const c of chemical) {
    const complex = fenyves.some((sheet) => sheet.predictions.get(edgeKey(c.pre, c.post)) === 'complex');
    if (complex && c.signSource !== 'expression' && c.signSource !== 'physiology') {
      complexRows.set(c.signSource, (complexRows.get(c.signSource) ?? 0) + 1);
    }
  }
  const fenyvesSignOf = (key: string): number | null => {
    const predictions = fenyves.map((sheet) => sheet.predictions.get(key)).filter((p) => p === '+' || p === '-');
    return predictions.length === 0 ? null : predictions[0] === '+' ? 1 : -1;
  };
  const fenyvesSigned = chemical.filter((c) => fenyvesSignOf(edgeKey(c.pre, c.post)) !== null).length;
  const overrideAgreement = { same: 0, opposite: 0, unsigned: 0 };
  for (const o of overrides) {
    const sign = fenyvesSignOf(edgeKey(o.pre, o.post));
    overrideAgreement[sign === null ? 'unsigned' : sign === o.sign ? 'same' : 'opposite'] += 1;
  }
  const muscleSections = new Map<string, { sign: number; sections: number }>();
  for (const j of data.neuromuscular) {
    const entry = muscleSections.get(j.pre) ?? { sign: j.sign, sections: 0 };
    entry.sections += j.sections;
    muscleSections.set(j.pre, entry);
  }
  const muscleCells = (sign: number): string[] =>
    [...muscleSections]
      .filter(([, v]) => v.sign === sign)
      .map(([n]) => n)
      .sort();
  const muscleSectionsOf = (sign: number): number =>
    [...muscleSections.values()].filter((v) => v.sign === sign).reduce((sum, v) => sum + v.sections, 0);
  const nmjSections = data.neuromuscular.reduce((sum, j) => sum + j.sections, 0);
  const oscillators = (kind: string): string[] => data.neurons.filter((n) => n.oscillator === kind).map((n) => n.name);

  return [
    '# Data build report',
    GENERATED,
    `What \`npm run data:build\` read, kept, ignored and assigned when it wrote \`public/data/wormlight.v1.json\`. The connectome comes from the Quantum Nematode export at \`${exportCommit.slice(0, 12)}\`.`,
    '## Counts',
    table(
      ['Element', 'Count'],
      [
        ['Neurons', String(data.neurons.length)],
        ['Body wall muscles', String(data.muscles.length)],
        [
          'Chemical connections',
          `${connections} (${sections} sections, ${chemical.filter((c) => c.pre === c.post).length} autapses)`,
        ],
        ['Gap-junction pairs', `${data.gap.length} (${data.gap.reduce((sum, g) => sum + g.sections, 0)} sections)`],
        [
          'Neuromuscular connections',
          `${data.neuromuscular.length} from ${muscleSections.size} neurons (${nmjSections} sections)`,
        ],
      ],
    ),
    '## Chemical synapse signs (PLAN §2.4)',
    table(
      ['Step', 'Source', 'Connections', 'Sections'],
      [
        ['1', 'Cited physiology', bySource.physiology, 'physiology'],
        ['2', 'Fenyves et al. 2020 expression prediction', bySource.expression, 'expression'],
        ['3', 'Transmitter rule: ACh and Glu +, GABA −', bySource.rule, 'rule'],
        ['4', 'No basis: no fast effect', bySource.none, 'none'],
      ].map(([step, label, counts]) => {
        const c = counts as { connections: number; sections: number };
        return [
          step as string,
          label as string,
          `${c.connections} (${percent(c.connections, connections)})`,
          `${c.sections} (${percent(c.sections, sections)})`,
        ];
      }),
    ),
    `Fenyves's prediction signs ${fenyvesSigned} connections. The build uses a Fenyves sign only where the presynaptic transmitter it rests on is one of the cell's identities in Wang et al. 2024, which sets aside the ${setAside.length} connections listed below. Of the ${overrides.length} physiology overrides, ${overrideAgreement.same} fall on connections it signs the same way, ${overrideAgreement.opposite} on connections it signs the other way, and ${overrideAgreement.unsigned} on connections it leaves unsigned. Of the connections Fenyves calls "complex", ${complexRows.get('rule') ?? 0} take the transmitter rule's sign and ${complexRows.get('none') ?? 0} have none.`,
    '### Fenyves signs set aside',
    `Fenyves's prediction for a connection rests on the primary transmitter it assigns the presynaptic cell, from the expression data available in 2020. Wang et al. 2024's knock-in atlas records no release of that transmitter by these cells, so the prediction has no footing, and each connection falls through to the transmitter rule: ${setAside.filter((c) => data.chemical.find((d) => d.pre === c.pre && d.post === c.post)?.signSource === 'rule').length} of them take its sign and ${setAside.filter((c) => data.chemical.find((d) => d.pre === c.pre && d.post === c.post)?.signSource === 'none').length} have none.`,
    table(
      ['Presynaptic cell', 'Fenyves transmitter', 'Wang et al. 2024 identities', 'Connections', 'Sections'],
      [...new Set(setAside.map((c) => c.pre))].sort(byCodeUnit).map((pre) => {
        const ofCell = setAside.filter((c) => c.pre === pre);
        const identities = data.neurons.find((n) => n.name === pre)?.transmitters ?? [];
        return [
          pre,
          ofCell[0].transmitter ?? 'none',
          identities.join(', ') || 'none',
          String(ofCell.length),
          String(ofCell.reduce((sum, c) => sum + c.sections, 0)),
        ];
      }),
    ),
    '### Physiology overrides (`data/sign-overrides.csv`)',
    table(
      ['Connection', 'Sign', 'Citation', 'Evidence'],
      overrides.map((o) => [`${o.pre} → ${o.post}`, signText(o.sign), o.citation, o.evidence]),
    ),
    '### The Fenyves files',
    table(
      ['File', 'Cook connections predicted', 'Rows ignored (not Cook connections)', 'Neurons absent'],
      fenyves.map((f) => [
        f.label,
        String(f.predictions.size),
        String(f.ignoredRows.length),
        `${f.absentNeurons.length}: ${f.absentNeurons.join(', ')}`,
      ]),
    ),
    ...fenyves.map((f) => `Ignored rows in ${f.label}: ${f.ignoredRows.join(', ') || 'none'}.`),
    '## Neuromuscular signs (PLAN §4.4)',
    `Each presynaptic cell's primary release identity decides: acetylcholine excites and GABA inhibits, through the body wall muscle's receptors (Richmond & Jorgensen 1999); any other identity has no fast effect. Cells with a second identity take their primary one.`,
    table(
      ['Sign', 'Cells', 'Sections', 'Which'],
      [
        ['+', String(muscleCells(1).length), String(muscleSectionsOf(1)), 'cholinergic cells'],
        ['−', String(muscleCells(-1).length), String(muscleSectionsOf(-1)), muscleCells(-1).join(', ')],
        ['0', String(muscleCells(0).length), String(muscleSectionsOf(0)), muscleCells(0).join(', ')],
      ],
    ),
    '## Anatomy',
    `The body frame runs from ${frame.noseUm.toFixed(1)} µm (the most anterior point of any neuron, at the nose) to ${frame.tailUm.toFixed(1)} µm (the most posterior), ${(frame.tailUm - frame.noseUm).toFixed(1)} µm in all, and positions are fractions of it. The Virtual Worm is posed with a dorsoventral bend, so positions measured along y are a projection; the midline itself is about 5% longer. ${axes.leftLarger} of ${axes.pairs} left/right pairs have the left cell at larger x, and at the nose all ${axes.nosePairs} dorsal sensory dendrites (CEP, IL1, IL2, OLQ, URA, URY) end at larger z than their ventral partners, confirming the axes where they can be read.`,
    table(
      ['Neuron', 'Senses', 'Where (fraction of body length)'],
      data.neurons
        .filter((n) => n.sensing.kind !== 'none')
        .map((n) => [
          n.name,
          n.sensing.kind === 'tip' ? 'at its dendrite tip' : 'along its process',
          n.sensing.kind === 'tip'
            ? String(n.sensing.s)
            : n.sensing.kind === 'field'
              ? `${n.sensing.s0}–${n.sensing.s1}`
              : '',
        ]),
    ),
    `Rhythm generators: ${oscillators('A').length} A-type (${oscillators('A').join(', ')}), ${oscillators('B').length} B-type (${oscillators('B').join(', ')}) and ${oscillators('headSwitch').length} head-switch neurons (${oscillators('headSwitch').join(', ')}).`,
    `Muscles sit on one grid of 24 slots per quadrant, so the quadrants line up; the ventral-left quadrant's 23rd and last cell covers the last two slots, because Cook's innervation matches it to vBWMR24 (PLAN §4.4, level 0).`,
    '## Eigenworm basis',
    `The pinned basis for checkpoint 1 has ${eigenworms.modes} modes over ${eigenworms.angles} tangent angles, which checkpoint 1 reads head first (an inferred orientation; see \`DATA_SOURCES.md\`). Its columns are orthonormal to within ${eigenworms.orthonormalError.toExponential(1)}, column ${eigenworms.rotationMode} is the constant rotation mode, and the first four modes, the ones checkpoint 1 uses, are free of rotation. It is read from its pinned URL and never redistributed.`,
    '## Starting postures',
    `The pinned real postures, which checkpoints 0 and 1 start their trials from, are ${grouped(postures.count)} rows of ${postures.angles} tangent angles, each with its mean removed to within ${postures.largestMean.toExponential(1)} rad. The first four eigenworms capture ${(100 * postures.captured).toFixed(2)}% of their variance, by the harness's own measure (PLAN §7.4). They are read from their pinned URL and never redistributed.`,
  ].join('\n\n');
}
