// Generated by `npm run data:build` from data/sign-overrides-s.csv; never edit it by hand. Track S's measured signs
// (DECISIONS.md, 2026-10-01): every chemical sign for which a response was recorded in the postsynaptic cell to a
// manipulation targeted at the presynaptic cell, which only track S's model applies until its fit is chosen.

import type { CitationId } from '../science/citations.ts';

export interface TrackSSign {
  pre: string;
  post: string;
  sign: 1 | -1;
  citation: CitationId;
}

export const TRACK_S_SOURCE = {
  path: 'data/sign-overrides-s.csv',
  sha256: '05bdb533e44a6ac1ddc5c682a6a0438ee585dd8c239e4bae1e4c97b0188c864b',
} as const;

export const TRACK_S_SIGNS: readonly TrackSSign[] = [
  { pre: 'AVAL', post: 'AVBL', sign: -1, citation: 'roberts2016' },
  { pre: 'AVAR', post: 'AVBL', sign: -1, citation: 'roberts2016' },
  { pre: 'AVAR', post: 'AVBR', sign: -1, citation: 'roberts2016' },
  { pre: 'AVBL', post: 'AVAL', sign: -1, citation: 'roberts2016' },
  { pre: 'AVBL', post: 'AVAR', sign: -1, citation: 'roberts2016' },
  { pre: 'AVBR', post: 'AVAL', sign: -1, citation: 'roberts2016' },
  { pre: 'AVBR', post: 'AVAR', sign: -1, citation: 'roberts2016' },
  { pre: 'PVPL', post: 'AVAL', sign: -1, citation: 'zhang2025' },
  { pre: 'PVPL', post: 'AVAR', sign: -1, citation: 'zhang2025' },
  { pre: 'PVPR', post: 'AVAL', sign: -1, citation: 'zhang2025' },
  { pre: 'PVPR', post: 'AVAR', sign: -1, citation: 'zhang2025' },
  { pre: 'AIBL', post: 'RIML', sign: -1, citation: 'piggott2011' },
  { pre: 'AIBL', post: 'RIMR', sign: -1, citation: 'piggott2011' },
  { pre: 'AIBR', post: 'RIML', sign: -1, citation: 'piggott2011' },
  { pre: 'AIBR', post: 'RIMR', sign: -1, citation: 'piggott2011' },
  { pre: 'AIBL', post: 'RIBR', sign: -1, citation: 'wang2020' },
  { pre: 'AIBR', post: 'RIBL', sign: -1, citation: 'wang2020' },
  { pre: 'SAADL', post: 'RIML', sign: -1, citation: 'huo2024' },
  { pre: 'SAADL', post: 'RIMR', sign: -1, citation: 'huo2024' },
  { pre: 'SAADR', post: 'RIML', sign: -1, citation: 'huo2024' },
  { pre: 'SAADR', post: 'RIMR', sign: -1, citation: 'huo2024' },
  { pre: 'SAAVL', post: 'RIML', sign: -1, citation: 'huo2024' },
  { pre: 'SAAVL', post: 'RIMR', sign: -1, citation: 'huo2024' },
  { pre: 'SAAVR', post: 'RIML', sign: -1, citation: 'huo2024' },
  { pre: 'SAAVR', post: 'RIMR', sign: -1, citation: 'huo2024' },
  { pre: 'PVPL', post: 'AVBL', sign: 1, citation: 'zhang2025' },
  { pre: 'PVPL', post: 'AVBR', sign: 1, citation: 'zhang2025' },
  { pre: 'PVPR', post: 'AVBL', sign: 1, citation: 'zhang2025' },
  { pre: 'PVPR', post: 'AVBR', sign: 1, citation: 'zhang2025' },
  { pre: 'DVC', post: 'AVAL', sign: 1, citation: 'zhang2025' },
  { pre: 'DVC', post: 'AVAR', sign: 1, citation: 'zhang2025' },
  { pre: 'AIYL', post: 'AIZL', sign: -1, citation: 'li2014' },
  { pre: 'AIYR', post: 'AIZR', sign: -1, citation: 'li2014' },
  { pre: 'AIYL', post: 'RIBL', sign: 1, citation: 'li2014' },
  { pre: 'AIYR', post: 'RIBR', sign: 1, citation: 'li2014' },
  { pre: 'AIYL', post: 'RIAL', sign: -1, citation: 'liu2018' },
  { pre: 'AIYR', post: 'RIAR', sign: -1, citation: 'liu2018' },
  { pre: 'AIZL', post: 'RIAL', sign: 1, citation: 'lin2024' },
  { pre: 'AIZR', post: 'RIAR', sign: 1, citation: 'lin2024' },
  { pre: 'AVAL', post: 'VA5', sign: 1, citation: 'liu2017' },
  { pre: 'AVAR', post: 'VA5', sign: 1, citation: 'liu2017' },
];
